all:  mapfile2 genintsfile2  

CFLAGS= -g -Wall 
 

mapfile2: mapfile2.c
	gcc -o mapfile2 $(CFLAGS) mapfile2.c 

 
genintsfile2: genintsfile2.c
	gcc -o genintsfile2 $(CFLAGS) genintsfile2.c 	

 
	
clean:
	rm -rf   mapfile2 genintsfile2  

