
all: files0 files1 dup0  


files0: files0.c
	gcc -o files0 -Wall files0.c

files1: files1.c
	gcc -o files1 -Wall files1.c	
	
	
dup0: dup0.c
	gcc -o dup0 -Wall dup0.c

	
clean:
	rm -rf files0 files1 dup0   

